name: black-action
on: [push, pull_request]
jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Black
        run: pip install black==25.1.0
        
      - name: Run Black
        run: black --check --diff .